// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupRolloutPrefs.network.cookie.cookieBehavior", 4);
user_pref("app.normandy.user_id", "9f59e7e6-4f3a-4c22-a0ec-7613bd889dcd");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1580383867);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 2262);
user_pref("browser.cache.disk.capacity", 686080);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1580383836);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 81);
user_pref("browser.newtabpage.activity-stream.impressionId", "{beb362b9-1e25-473d-a83b-b586fe97dab2}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1580383855630");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1580387455630");
user_pref("browser.search.region", "IN");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1580383853");
user_pref("browser.slowStartup.averageTime", 9294);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20190718161435");
user_pref("browser.startup.homepage_override.mstone", "68.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1580383842);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1580383850088");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "68.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "22ab351dfe754d22ada5388f50ebf03c");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "68.0.1");
user_pref("extensions.lastPlatformVersion", "68.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"def9e152-cd28-41b5-ad5d-aa4d47c8755f\",\"fxmonitor@mozilla.org\":\"24eeeab6-084e-4e91-9122-4f2578cb12bd\",\"screenshots@mozilla.org\":\"80b08955-ac4d-42f1-99af-04edc5a9a59f\",\"webcompat-reporter@mozilla.org\":\"51156702-00ca-4dd8-8c1a-b1b40bee65fa\",\"webcompat@mozilla.org\":\"9b699c62-71c1-421d-8c17-7e97f86bbf65\",\"default-theme@mozilla.org\":\"5fa11a11-5f94-4bd8-8374-f43efbf8c780\",\"google@search.mozilla.org\":\"470b35d5-4207-44bb-84c3-21d43793becd\",\"amazondotcom@search.mozilla.org\":\"fac403fb-114b-4e04-9299-14ea9bc8106a\",\"bing@search.mozilla.org\":\"fd26e926-7c6b-412c-825a-4f30bb307674\",\"ddg@search.mozilla.org\":\"0a7bdff6-b611-4d09-985d-a611262a72a0\",\"ebay@search.mozilla.org\":\"508b6cf2-1b75-4f06-b91e-4e4eabc44bc2\",\"twitter@search.mozilla.org\":\"36ee0b40-0bee-4fb2-bc49-580693941dd8\",\"wikipedia@search.mozilla.org\":\"a732f3b9-d8b6-4aa7-90dc-c41cadcdc3d2\"}");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "79f2f514-d866-4021-b571-68665e6b95a4");
user_pref("security.sandbox.plugin.tempDirSuffix", "a99947c6-54da-4d9d-85cb-7d7a7c021f9d");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1580383832);
user_pref("toolkit.telemetry.cachedClientID", "f11035a4-0aff-4123-a905-17eb2a8cf409");
user_pref("toolkit.telemetry.previousBuildID", "20190718161435");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
